### ISSUE TITLE
no data entries can be found at all

### ISSUE THREAD

**Issue by okurz** [hoffie/dkb-visa#11]
Since some days (did not use dkb-visa for some months in before) I can not get any data entries at all, anymore. Maybe webpage form changed again.
Running dkb-visa with pdb debugger and checking the form input IMHO the request URL is fine but the response has an empty block like
```
…
<input name="$$$event_search" type="hidden" value="search"/>
</form>
</div>
</div>
</div>
</div>
</div>
<div class="clearfix richfooter_wrap" id="richfooter_wrap">
…
```
where I would actually expect some data as I can see them with the firefox inspector. Does anyone still have success on dkb webpage?

**Comment by hoffie** [comment]
Seems like @cmusik has figured it out already. With his patch merged, things seem to work normally again! :)

**Comment by okurz** [comment]
yes, perfect. I would have closed the issue myself but did have the time to actually check the solution. Thanks to @hoffie and @cmusik.
@cmusik out of interest: I understand what #12 does but how did you find out what's missing? I stepped through the steps with a debugger and to me the request looked comparable to what I could see with firefox. What did you do to find the solution?

**Comment by cmusik** [comment]
@okurz I looked at the request headers with chrome (firefox works also). So I opened the debugger and clicked on request that I created. There you can see which parameters are send to the server. Then I looked at the code with pdb and saw that the parameter $$$event_search was wrong and that $event is needed. HTH.

**Comment by okurz** [comment]
awesome. thanks very much.
