### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by hakoerber** [hoffie/dkb-visa#18]
Hello,

it looks like `mechanize` is not available for python3.

I'm currently trying to integrate dkb-visa into my own script, which unfortunately is written in python3. Do you have any plans to migrate to python3? How could I help with the migration?

The following StackOverflow comment mentions some mechanize alternatives for python3, which might be helpful: https://stackoverflow.com/a/31774959

Anway, thank you for the awesome script!

**Comment by hoffie** [comment]
Hi. Thanks for your request and the SO link. Sadly, I currently don't have time to actively implement such a change. Of course, I would welcome any PRs which help with the migration.
In the meantime it would probably be nice to keep this working with both Python 2 and 3, if possible.
MechanicalSoup looks good and seems to be similar.
scrapy.org could also be an option, but seems to be bigger and may have more dependencies.

**Comment by hoffie** [comment]
Thanks to @stephanritscher we now have Python3 support. As time moved on and Python2 is officially deprecated, I don't see Python2 support as a priority anymore. Closing as fixed.
