### ISSUE TITLE
Unable to find transaction selection form

### ISSUE THREAD

**Issue by richi235** [hoffie/dkb-visa#19]
Last week and today (19.9.2019) I tried to obtain my transactions and got the following error message and stack trace:

```
richi@yang:~/Coding/dkb-visa$ ./dkb.py --userid XXXX --cardid YYYY --output dkb_visa_card_umsaetze.qif
Start time: 21.06.2019
PIN: 
Starting login as user XXXX...
Navigating to 'Umsätze'...
Selecting transactions in time frame 21.06.2019 - 18.09.2019...
Traceback (most recent call last):
  File "./dkb.py", line 493, in <module>
    fetcher.select_transactions(args.cardid, from_date, args.to_date)
  File "./dkb.py", line 242, in select_transactions
    br.form = form = self._get_transaction_selection_form()
  File "./dkb.py", line 168, in _get_transaction_selection_form
    raise RuntimeError("Unable to find transaction selection form")
RuntimeError: Unable to find transaction selection form
```

**Comment by hoffie** [comment]
Thanks for the report. I suspect this is related to the 2019-09-14 banking changes regarding login mechanisms. I guess you are asked about a TAN upon login now (at least I am). I have no idea how to properly integrate this yet.
If someone has, I'm happy to take ideas or PRs.

To be honest, I currently do not actively use this code. I may look into this as time permits, though.

**Comment by hoffie** [comment]
chipTAN should work thanks to @dingensundso's pull request.
Other TAN variants will still need more work or at least input about the actual HTML content.

**Comment by sbluhm** [comment]
I added a pull request to add DKB App support
#21

**Comment by hoffie** [comment]
I suppose chipTAN and appTAN are the most popular variants. Both should work now. Therefore I'm going to close this issue. Please open a new one if something still doesn't work.
Thanks again to @sbluhm and @dingensundso!
