### ISSUE TITLE
Add Github topics to the repository

### ISSUE THREAD

**Issue by mendel5** [hoffie/dkb-visa#25]
Hi, can you add the following topics to this repository?
* https://github.com/topics/dkb
* https://github.com/topics/banking
* https://github.com/topics/finance

Thanks!

**Comment by hoffie** [comment]
Hi @mendel5,

thanks for the suggestion and sorry for the really late reaction. Done now. :)

Kind regards,
Christian

**Comment by mendel5** [comment]
Hi @hoffie , no worries and thanks for your feedback!
